---
- hosts: webservers
  become: true
  tasks:
    - file:
        path: "{{ item }}"
        state: touch
      with_items:
           - /home/ansible/f1
           - /home/ansible/f2
           - /home/ansible/f3