---
- hosts: webservers
  become: true
  tasks:
    - file:
        path: "{{ item }}"
        state: directory
      with_items:
           - /home/ansible/d1
           - /home/ansible/d2
           - /home/ansible/d3