---
- hosts: webservers
  become: true
  tasks:
    - file:
        path: {{item}}
      with_item:
        state:
           - /home/ansible/dr1
           - /home/ansible/dr2
           - /home/ansible/dr3