---
- hosts: webservers
  become: true
  tasks:
    - file:
        path: {{ item }}
        state: directory
      with_items:
           - /home/ansible/dr1
           - /home/ansible/dr2
           - /home/ansible/dr3